### ISSUE TITLE
trackList.json style config?

### ISSUE THREAD

**Issue by colindaven** [cmdcolin/manytracks#5]
Hi Colin,

great idea, this will be immediately useful and saves config overhead. 

Is trackList.json style config also available ?

cheers
Colin

**Comment by cmdcolin** [comment]
Yep I think that is fine to add style configs. Here's a small example https://github.com/cmdcolin/manytracks/commit/1d3ff4537d23ecc32e208a70ffd5a56d30d99b6c

**Comment by cmdcolin** [comment]
If there is any other issue you run into let me know :) maybe i'll close for now

appreciate the positive feedback!
